# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -DenisViskov16@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    env:
      global:
        CODECOV_TOKEN="89b98c36-31f4-4401-b2e0-56a80e18360f"